<?php

namespace Vinyett\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InviteRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InviteRequestRepository extends EntityRepository
{
}