<?php

namespace Vinyett\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
Use Doctrine\ORM\Query\Expr as Expr;

use Vinyett\UserBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    /**
     * Finds a profile by a username and joins the photo
     * for profile.
     *
	 * @param string $username Username of the profile
	 *
     * @return User
     */
    public function findProfileByUsername($username) 
    { 

        $qb = $this->createQueryBuilder("u");
        
        $qb->where("u.username = :username")
           ->leftJoin('u.profile_photo', 'p', Expr\Join::WITH)
           ->setParameter("username", $username);
           
        return $qb->getQuery()->getSingleResult();

    }
}