parameters:
    affinity.manager.class: Vinyett\ConnectBundle\Services\AffinityManager

services:

    affinity.manager:
        class: %affinity.manager.class%
        arguments: [@doctrine.orm.entity_manager, @security.context]