services:
    sonata.admin.photo:
        class: Vinyett\PhotoBundle\Admin\PhotoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Global view", label: "Photos" }
        arguments:
            - ~
            - Vinyett\PhotoBundle\Entity\Photo
            - 'SonataAdminBundle:CRUD'