imports:
    - { resource: config_dev.yml }

framework:
    test: true
    session:
        storage_id: session.storage.filesystem
    profiler: { only_exceptions: false }

# enable the web profiler
web_profiler:
    toolbar: false
    intercept_redirects: false
        
swiftmailer:
    disable_delivery: true
