blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

RestBundle:
    resource: "@RestBundle/Resources/config/routing.yml"
    type: rest
    prefix:   /

ConnectBundle:
    resource: "@ConnectBundle/Resources/config/routing.yml"
    prefix:   /

ProfileBundle:
    resource: "@ProfileBundle/Resources/config/routing.yml"
    prefix:   /

CoreServicesBundle:
    resource: "@CoreServicesBundle/Resources/config/routing.yml"
    prefix:   /

PhotoBundle:
    resource: "@PhotoBundle/Resources/config/routing.yml"
    prefix:   /

StreamBundle:
    resource: "@StreamBundle/Resources/config/routing.yml"
    prefix:   /

UserBundle:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

StaticBundle:
    resource: "@StaticBundle/Resources/config/routing.yml"
    prefix:   /
    
NotificationBundle:
    resource: "@NotificationBundle/Resources/config/routing.yml"
    prefix:   /

# FOS user routing
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
admin_dashboard:
    pattern: /admin
    defaults: { _controller: SonataAdminBundle:Core:dashboard }

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
