security:
    acl:
        connection: default

    encoders:
        "FOS\UserBundle\Model\UserInterface": sha512
        
    providers:
        chain_provider:
            chain:
                providers: [in_memory, fos_userbundle]
        fos_userbundle:
            id: fos_user.user_manager        
        in_memory:
            memory:
                users:
                    user_test:  { password: testCase3224, roles: [ 'ROLE_USER' ] }
                    admin_test: { password: testCase3214, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: chain_provider
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    ~
            http_basic:
                provider: chain_provider
            switch_user: true
        
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_PREVIOUS_ADMIN: ROLE_ADMIN
        
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }