services:
    sonata.admin.post:
        class: Vinyett\BlogBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Blog", label: "Posts" }
        arguments:
            - ~
            - Vinyett\BlogBundle\Entity\Post
            - 'SonataAdminBundle:CRUD'
        calls:
            - [setSecurityContext, [@security.context]]