parameters:
    collection.rest.listener.class: Vinyett\RestBundle\Listener\CollectionPreserialize

services:
#    rest.example:
#        class: %rest.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
