<?php

namespace Vinyett\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{

    public function getMostRecentHomepagePost()
    {
        $qb = $this->createQueryBuilder("p");
        $qb->where("p.is_public = true AND p.is_front_page = true")
           ->orderBy("p.created_at", "DESC")
           ->setMaxResults(1);

        return $qb->getQuery()->getSingleResult();
    }

}