<?php

namespace Vinyett\PhotoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CollectionPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectionPhotoRepository extends EntityRepository
{
}