parameters:
#    core_services.example.class: Vinyett\CoreServicesBundle\Example
    text.extensions.class:  Vinyett\CoreServicesBundle\Extension\TextExtension
    time.extensions.class:  Vinyett\CoreServicesBundle\Extension\TimeTwigExtension
    html.purifier.class:   Vinyett\CoreServicesBundle\Services\Purifier

services:
    core_services.purifier:
        class: %html.purifier.class%

    text.extensions:
        class: %text.extensions.class%
        tags:
            - { name: twig.extension }
            
    time.extensions:
        class: %time.extensions.class%
        tags:
            - { name: twig.extension }
            
    vinyett.form.type.purified_textarea:
        class: Vinyett\CoreServicesBundle\Form\Type\PurifiedTextareaType
        arguments: [@vinyett.form.transformer.html_purifier]
        tags: 
            - { name: form.type, alias: purified_textarea }
            
    vinyett.form.transformer.html_purifier:
        class: Exercise\HTMLPurifierBundle\Form\HTMLPurifierTransformer
        arguments: [@exercise_html_purifier.default]
        
    security.acl.object_identity_retrieval_strategy:
        class: Vinyett\CoreServicesBundle\Security\Acl\Domain\ObjectIdentityRetrievalStrategy
        public: false
        arguments: [@doctrine.orm.entity_manager]