<?php

namespace Vinyett\NotificationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationPreferencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationPreferenceRepository extends EntityRepository
{
}
