<?php

namespace Vinyett\NotificationBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
	
	public function totalUnread($user)
	{ 
	
		$em = $this->getEntityManager();
		
		$query = $em->createQuery('SELECT COUNT(n.id) FROM Vinyett\NotificationBundle\Entity\Notification n WHERE n.owner = :user AND n.is_new = 1');
		$query->setParameter("user", $user);
		$count = $query->getSingleScalarResult();
		
		return $count;
	}
	
	//Function will be expanded in the future.
	public function getNotificationsListData($user) 
	{ 
	
		$em = $this->getEntityManager();
		
		$qb = $this->createqueryBuilder("n");
		$qb->add("where", $qb->expr()->eq("n.user", ":user"));
		$qb->add('orderBy', new Expr\OrderBy('n.created_at', 'DESC'));
		$qb->setMaxResults(10);
		$qb->setParameter("user", $user);
		
		$query = $qb->getQuery();
		
		return $query->getResult();
	
	}

}