<?php

namespace Vinyett\NotificationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubscriptionListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionListRepository extends EntityRepository
{

    /**
     * Finds a single subscription list based on an identity (which can virtually
     * be anything) and an event.
     * 
     * @access public
     * @param mixed $identity
     * @param mixed $event
     * @return void
     */
    public function load($identity, $event)
    { 
        $qb = $this->createQueryBuilder("s");
        $qb//->addSelect(array("u"))
		   ->where("s.object_identity = :identity AND s.event = :event")
		   //->leftJoin("s.subscribers", "u")
		   ;
		$qb->setParameters(array("identity" => $identity, "event" => $event));
		$qb->setMaxResults(1);
		
		$query = $qb->getQuery();
		try {
    		$list = $query->getSingleResult();
        } catch (\Exception $e) {
            $list = false;
        }
        
        return $list;
    }

}
