parameters:
#    static.example.class: Vinyett\StaticBundle\Example

services:
#    static.example:
#        class: %static.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
