<?php

namespace Vinyett\StreamBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{

    /**
     * Fetches activities since the last feed update (or last 150) for the 
     * connections involved. 
     *
	 * @param ArrayCollection $connections Array of connections to fetch activities for
	 *
     * @return ArrayCollection
     */
    public function fetchActivitiesByConnections($updated, $connections) 
    { 
        $qb = $this->createQueryBuilder("a");
        $qb->select(array("a", "p"))
           ->where("a.actor IN (:actors)")
           ->leftJoin("a.actor", "p")
           ->orderBy("a.created_at", "DESC")
           //->groupBy("a.photo")
           ->setMaxResults(150);
        
        $qb->setParameters(array("actors" => $connections));
        
        $query = $qb->getQuery();      
        
        return $query->getResult();

    }

}